"""1.03: 8 bang proxy dau tien

Revision ID: 7429285e7b45
Revises:
Create Date: 2026-10-10 01:04:19.944549
"""

import sqlalchemy as sa
from alembic import op

revision = "7429285e7b45"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account_slots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=16), server_default="api", nullable=False),
        sa.Column("api_key_enc", sa.Text(), nullable=True),
        sa.Column("cookie_enc", sa.Text(), nullable=True),
        sa.Column("group_name", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("cooldown_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_limit_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rate_limit_window_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_failure_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'cooling', 'auth_failed', 'disabled')",
            name="ck_account_slots_status",
        ),
        sa.CheckConstraint("type IN ('api', 'web')", name="ck_account_slots_type"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_account_slots_group_name"), "account_slots", ["group_name"], unique=False
    )
    op.create_index(
        "ix_account_slots_status_cooldown",
        "account_slots",
        ["status", "cooldown_until"],
        unique=False,
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("plan_credits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("bonus_credits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("used_credits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("plan_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_ip", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'locked')", name="ck_customers_status"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hwid"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), server_default="plan", nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("credits", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('plan', 'topup')", name="ck_plans_kind"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "system_voices",
        sa.Column("voice_id", sa.String(length=256), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model_compatibility", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("voice_id"),
    )
    op.create_table(
        "activation_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by_customer_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(["used_by_customer_id"], ["customers.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(
        op.f("ix_activation_keys_batch_id"), "activation_keys", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_activation_keys_plan_id"), "activation_keys", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_activation_keys_used_by_customer_id"),
        "activation_keys",
        ["used_by_customer_id"],
        unique=False,
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("hwid", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_customer_id"), "refresh_tokens", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"), "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_table(
        "usage_log",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="reserved", nullable=False),
        sa.Column("chars_reserved", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("chars_used", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("voice_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('reserved', 'committed', 'released')", name="ck_usage_log_status"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["account_slots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_usage_log_customer_created", "usage_log", ["customer_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_usage_log_customer_id"), "usage_log", ["customer_id"], unique=False)
    op.create_index(op.f("ix_usage_log_slot_id"), "usage_log", ["slot_id"], unique=False)
    op.create_index(
        "ix_usage_log_status_created", "usage_log", ["status", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_log_status_created", table_name="usage_log")
    op.drop_index(op.f("ix_usage_log_slot_id"), table_name="usage_log")
    op.drop_index(op.f("ix_usage_log_customer_id"), table_name="usage_log")
    op.drop_index("ix_usage_log_customer_created", table_name="usage_log")
    op.drop_table("usage_log")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_customer_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_activation_keys_used_by_customer_id"), table_name="activation_keys")
    op.drop_index(op.f("ix_activation_keys_plan_id"), table_name="activation_keys")
    op.drop_index(op.f("ix_activation_keys_batch_id"), table_name="activation_keys")
    op.drop_table("activation_keys")
    op.drop_table("system_voices")
    op.drop_table("system_settings")
    op.drop_table("plans")
    op.drop_table("customers")
    op.drop_index("ix_account_slots_status_cooldown", table_name="account_slots")
    op.drop_index(op.f("ix_account_slots_group_name"), table_name="account_slots")
    op.drop_table("account_slots")
    # ### end Alembic commands ###
